name: OlympaCreatif
version: 0.1
author: Bullobily

main: fr.olympa.olympacreatif.OlympaCreatifMain

depend: [OlympaCore]
softdepend: [NoteBlockAPI, WorldEdit, AsyncWorldEdit, FastAsyncWorldEdit, goBrush, goPaint]
api-version: 1.16