name: OlympaCreatif
version: @plugin_version@
author: Bullobily

main: fr.olympa.olympacreatif.OlympaCreatifMain

depend: [OlympaCore]
softdepend: [NoteBlockAPI, WorldEdit, AsyncWorldEdit, FastAsyncWorldEdit, goBrush, goPaint]
api-version: 1.16
website: https://gitlab.com/olympa/olympacreatif