name: OlympaCreatif
version: 0.1
author: Bullobily

main: fr.olympa.olympacreatif.OlympaCreatifMain

depend: [OlympaCore]
softdepend: [WorldEdit, FastAsyncWorldEdit, NoteBlockAPI]
api-version: 1.16