name: OlympaCreatif
version: 0.1
author: Bullobily

main: fr.olympa.olympacreatif.OlympaCreatifMain

depend: [OlympaCore]
softdepend: [WorldEdit, AsyncWorldEdit, FastAsyncWorldEdit, JukeBox]
api-version: 1.15