name: OlympaCreatif
version: 0.1
author: Bullobily

load: STARTUP
main: fr.olympa.olympacreatif.OlympaCreatifMain

depend: [OlympaCore]
softdepend: [WorldEdit, AsyncWorldEdit, LuckPerms]
api-version: 1.15